### PR TITLE
Upgrade the heartbeat to version v0.14.43

### PR DESCRIPTION
**Pull request by cristinaleonr**
This PR upgrades the heartbeat version to pick up change https://github.com/m-lab/locate/pull/174.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/861)

### CODE REVIEW

**Review by nkinkade — APPROVED** [review]
LGTM

**Review by cristinaleonr — COMMENTED** [review]
Let me know when you've done your testing and we'll merge it.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/861#-:-NlZFi3j3iVPcuqnNOqx:buq1mj6)* status: 0 of 1 approvals obtained

**Review by cristinaleonr — COMMENTED** [review]
> Let me know when you've done your testing and we'll merge it.

@nkinkade tagging you in this comment, in case you missed it.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/861#-:-Nmaomga-qzOfbHKv_4X:bw9erkt)* status: 0 of 1 approvals obtained

**Review by nkinkade — COMMENTED** [review]
Sorry, I didn't get a chance to test this before the holiday break. I will test it as soon as I'm back on the 2nd or 3rd.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/861#-:-NmghZWL7wO1OkEqfLFv:bu13cgt)* status: 0 of 1 approvals obtained

**Pull request merged**
