### PR TITLE
Add -label flags

### PR DESCRIPTION
**Pull request by cristinaleonr**
Sample files (converted from .json to .txt because Github does not support attaching .json files):

- ndt5

[ndt-pfp95_1639689342_00000000001E90D6.txt](https://github.com/m-lab/k8s-support/files/7995775/ndt-pfp95_1639689342_00000000001E90D6.txt)

- ndt7

[ndt7-upload-20220203T020256.847639073Z.mlab1-pdx0t_1642181106_0000000000036A88.txt](https://github.com/m-lab/k8s-support/files/7995776/ndt7-upload-20220203T020256.847639073Z.mlab1-pdx0t_1642181106_0000000000036A88.txt)
[ndt7-download-20220203T020246.399133503Z.mlab1-pdx0t_1642181106_0000000000036A83.txt](https://github.com/m-lab/k8s-support/files/7995777/ndt7-download-20220203T020246.399133503Z.mlab1-pdx0t_1642181106_0000000000036A83.txt)

This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642)

### CODE REVIEW

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642)* status: 0 of 1 approvals obtained

___
*[k8s/daemonsets/templates.jsonnet, line 2 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9uYm3BuIMnZ6K8sA:-Mv-9uYn3xUew93jbgXC:bfgdzuo) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/templates.jsonnet#L2)):*
> ```Jsonnet
> local ndtVersion = 'v0.20.7';
> local ndtCanaryVersion = 'v0.20.6';
> ```

Does this version need to be updated, too?
___
*[k8s/daemonsets/experiments/ndt-virtual.jsonnet, line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9zH12rS4JYVtzobB:-Mv-9zH12rS4JYVtzobC:b4t87xl) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/experiments/ndt-virtual.jsonnet#L40)):*
> ```Jsonnet
>               '-key=/certs/tls.key',
>               '-cert=/certs/tls.crt',
>               '-label=machine-type=virtual',
> ```

Are there any other flags we want to add here at this time?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642)* status: 0 of 1 approvals obtained (waiting on @nkinkade and @robertodauria)

___
*[k8s/daemonsets/templates.jsonnet, line 2 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9uYm3BuIMnZ6K8sA:-Mv-HkLRA61ynILjQW-C:b-emo7eq) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/templates.jsonnet#L2)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Does this version need to be updated, too?
</blockquote></details>

We may not have any canary nodes active atm but keeping them equal when there is none seems like a good idea.

@robertodauria can you confirm this is preferable?
___
*[k8s/daemonsets/experiments/ndt-virtual.jsonnet, line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9zH12rS4JYVtzobB:-Mv-I2Na7t9ZPG59leXO:b-qzd1zt) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/experiments/ndt-virtual.jsonnet#L40)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Are there any other flags we want to add here at this time?
</blockquote></details>

@nkinkade when he returns.

Ideally we would find a way to plumb metadata from the GCE metadata server here including: region name, public IP, service tier, machine type (whoops this may be a name collision https://cloud.google.com/compute/docs/machine-types ). Let's consider the right names for a moment... the sandbox cloud deployments don't matter yet, I guess it's the other labels on the production deployments that give me pause for this PR now.

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr and @nkinkade)

___
*[k8s/daemonsets/templates.jsonnet, line 2 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9uYm3BuIMnZ6K8sA:-Mv-Mspa-xuPmJfx7NQa:b-2u1kst) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/templates.jsonnet#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

We may not have any canary nodes active atm but keeping them equal when there is none seems like a good idea.

@robertodauria can you confirm this is preferable?
</blockquote></details>

It seems safer to me. In case a node gets labeled with `mlab/ndt-version=canary` by mistake we won't deploy an older version of ndt-server there.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[k8s/daemonsets/experiments/ndt-virtual.jsonnet, line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9zH12rS4JYVtzobB:-Mv-tuto0r2uabMib9An:biuce0q) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/experiments/ndt-virtual.jsonnet#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

@nkinkade when he returns.

Ideally we would find a way to plumb metadata from the GCE metadata server here including: region name, public IP, service tier, machine type (whoops this may be a name collision https://cloud.google.com/compute/docs/machine-types ). Let's consider the right names for a moment... the sandbox cloud deployments don't matter yet, I guess it's the other labels on the production deployments that give me pause for this PR now.
</blockquote></details>

I imagine it could be possible to plumb some of the VM data through to ndt-server. Perhaps there could be a small service which runs when a VM boots that would collect this information and write it out to a file. ndt-server could attempt to read this file when it starts. Or, since most of this information is available once the virtual site is created, we could potentially plumb it into a ConfigMap (later to env variables), which could be used to set flag values in the DaemonSet manifest.

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr, @robertodauria, and @stephen-soltesz)

___
*[k8s/daemonsets/templates.jsonnet, line 2 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9uYm3BuIMnZ6K8sA:-Mv033NV5B9fFiNIWQfi:b-bw8e1h) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/templates.jsonnet#L2)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

It seems safer to me. In case a node gets labeled with `mlab/ndt-version=canary` by mistake we won't deploy an older version of ndt-server there.
</blockquote></details>

Updated!

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[k8s/daemonsets/templates.jsonnet, line 2 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9uYm3BuIMnZ6K8sA:-MvJiNdEAMoZcvYGeYiS:bct10nm) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/templates.jsonnet#L2)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Updated!
</blockquote></details>

Please add a comment that the canary version is expected to be greater than or equal to the current stable version.
___
*[k8s/daemonsets/experiments/ndt-virtual.jsonnet, line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9zH12rS4JYVtzobB:-MvJineI3459j5uwIGAi:b-4fzs8q) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/experiments/ndt-virtual.jsonnet#L40)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I imagine it could be possible to plumb some of the VM data through to ndt-server. Perhaps there could be a small service which runs when a VM boots that would collect this information and write it out to a file. ndt-server could attempt to read this file when it starts. Or, since most of this information is available once the virtual site is created, we could potentially plumb it into a ConfigMap (later to env variables), which could be used to set flag values in the DaemonSet manifest.
</blockquote></details>

I like that idea - which way would be simpler? let's do it!

Still wondering about a better name for "machine-type" that isn't ambiguous with GCE "machine-types"...

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642)* status: 0 of 1 approvals obtained (waiting on @nkinkade and @stephen-soltesz)

___
*[k8s/daemonsets/templates.jsonnet, line 2 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9uYm3BuIMnZ6K8sA:-MvQX5_G2RW0oKavpshY:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/templates.jsonnet#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add a comment that the canary version is expected to be greater than or equal to the current stable version.
</blockquote></details>

Done.
___
*[k8s/daemonsets/experiments/ndt-virtual.jsonnet, line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9zH12rS4JYVtzobB:-MvQXCCe5yjmBOFkkMOp:bi6595g) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/experiments/ndt-virtual.jsonnet#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

In our current k8s configs we use the annotation "mlab/type=physical" or "mlab/type=virtual" -- could we simply use `-label=type=virtual` or `type=physical` here? and reserve `machine-type=` for either the GCE or physical model name (e.g. n1-standard-2, or R630 / R640, etc)?

I've updated the NDT labels design doc with suggestions for this idea with additional helpful labels. https://docs.google.com/document/d/1gUlMEkPEeyGUZIv3qcIvFcOukdIOrtvQ4sBCaY4l1xY/edit#heading=h.1ztk51of8ugx
</blockquote></details>

Great, thanks!

When I asked the initial question the main thing I wanted to know was whether this config should also specify a `deployment` flag (e.g., stable, or something else)?

**Review by stephen-soltesz — APPROVED** [review]
We've discussed conversationally a plan for more complete metadata from the GCE environment. As a first round, this PR :lgtm: (please see last comment for labels on the virtual config.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642#-:-MvQaGxCDJx4gLIoTVs3:b-ca616e)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[k8s/daemonsets/experiments/ndt-virtual.jsonnet, line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/642#-Mv-9zH12rS4JYVtzobB:-MvQ_zQnEaVHSZEe0MxE:biomtxw) ([raw file](https://github.com/m-lab/k8s-support/blob/4bf36c3366d4839a119fbb070343a655d3d62efc/k8s/daemonsets/experiments/ndt-virtual.jsonnet#L40)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Great, thanks!

When I asked the initial question the main thing I wanted to know was whether this config should also specify a `deployment` flag (e.g., stable, or something else)?
</blockquote></details>

Ah, got it. Please also add the `deployment=stable` case here. That refers to the ndt-server itself ... and this isn't deployed to production yet so we have time to get the other metadata labels before the archival data needs them.

**Review by cristinaleonr — COMMENTED** [review]
Done, thanks.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/642#-:-MvQoNf3BErCnQw9XehY:b-dtkdrq)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

**Pull request merged**
