### PR TITLE
Revert "Runs most containers as non-root (#785)"

### PR DESCRIPTION
**Pull request by nkinkade**
This reverts commit 501e4ddeb745893f57ff2ce3de37d36ba833714c.

There were multiple levels of breakage with this commit. I need more time to sort them all out in sandbox.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/788)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: - One question. One request.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/788#-:-NR_FAwaDVsS6Oa1aCjZ:b-jh8aur)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`k8s/daemonsets/core/utilization.jsonnet` line 1 at r1](https://reviewable.io/reviews/m-lab/k8s-support/788#-NR_Ei-B3Ug5tZ0ZD3BJ:-NR_Ei-B3Ug5tZ0ZD3BK:b-m77tfd) ([raw file](https://github.com/m-lab/k8s-support/blob/70e32616c14bbb9c618dcf45c570d91159701b77/k8s/daemonsets/core/utilization.jsonnet#L1)):*
> ```Jsonnet
> local exp = import '../templates.jsonnet';
> ```

Why was utilization removed from the previous PR?
___
*[`k8s/daemonsets/experiments/wehe.jsonnet` line 53 at r1](https://reviewable.io/reviews/m-lab/k8s-support/788#-NR_F0r2804lHhnRDQvQ:-NR_F0r2804lHhnRDQvR:b-vkuwkx) ([raw file](https://github.com/m-lab/k8s-support/blob/70e32616c14bbb9c618dcf45c570d91159701b77/k8s/daemonsets/experiments/wehe.jsonnet#L53)):*
> ```Jsonnet
>               '-envelope.verify-key=/verify/jwk_sig_EdDSA_locate_20200409.pub',
>               # TODO(soltesz): Restore functionality after 2023/02/01.
>               '-envelope.token-required=false',
> ```

Please keep `=true` here. This should be a safe change to preserve forward.

**Review by nkinkade — COMMENTED** [review]
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/788#-:-NR_HFFFBj4WMwZy8eFt:b-833305)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`k8s/daemonsets/experiments/wehe.jsonnet` line 53 at r1](https://reviewable.io/reviews/m-lab/k8s-support/788#-NR_F0r2804lHhnRDQvQ:-NR_HEQT2GVRG9anNYC1:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/70e32616c14bbb9c618dcf45c570d91159701b77/k8s/daemonsets/experiments/wehe.jsonnet#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please keep `=true` here. This should be a safe change to preserve forward.
</blockquote></details>

Done.
___
*[`k8s/daemonsets/core/utilization.jsonnet` line 1 at r1](https://reviewable.io/reviews/m-lab/k8s-support/788#-NR_Ei-B3Ug5tZ0ZD3BJ:-NR_Fys8C97a4IPv1DSc:b-jvu5kk) ([raw file](https://github.com/m-lab/k8s-support/blob/70e32616c14bbb9c618dcf45c570d91159701b77/k8s/daemonsets/core/utilization.jsonnet#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Why was utilization removed from the previous PR?
</blockquote></details>

It wasn't doing anything, as far as I know. It was the old, outdated DaemonSet that ran utility-support in order to get switch metrics, before we had Disco v2:

```
image: 'measurementlab/utility-support:v2.0.11',
```

I will remove it again from this PR.

**Review by stephen-soltesz — APPROVED** [review]
Thank you.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/788#-:-NR_HbT857LEMWCZCcBy:b-tretpm)* status: 0 of 1 approvals obtained

___
*[`k8s/daemonsets/core/utilization.jsonnet` line 1 at r1](https://reviewable.io/reviews/m-lab/k8s-support/788#-NR_Ei-B3Ug5tZ0ZD3BJ:-NR_Hdzc4s1kKH7hg2fD:b-8livvy) ([raw file](https://github.com/m-lab/k8s-support/blob/70e32616c14bbb9c618dcf45c570d91159701b77/k8s/daemonsets/core/utilization.jsonnet#L1)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It wasn't doing anything, as far as I know. It was the old, outdated DaemonSet that ran utility-support in order to get switch metrics, before we had Disco v2:

```
image: 'measurementlab/utility-support:v2.0.11',
```

I will remove it again from this PR.
</blockquote></details>

Oooh! Got it.

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/ops-tracker/issues/1650

**Pull request merged**
