### PR TITLE
Save binaries in epoxy images rather than during the ePoxy action

### PR DESCRIPTION
**Pull request by pboothe**
Second part of fixing https://github.com/m-lab/k8s-support/issues/28

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/30)

### CODE REVIEW

**Comment by pboothe** [comment]
https://github.com/m-lab/epoxy-images/pull/52 adds the binaries to the epoxy images.

**Comment by pboothe** [comment]
Updated in response to comments, then merging.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[node/push_setup.sh, line 2 at r1](https://reviewable.io/reviews/m-lab/k8s-support/30#-LC4G_q1EfoiVcKzKZ1k:-LC4LuJI7b2lj_i0mDKT:b28jrdr) ([raw file](https://github.com/m-lab/k8s-support/blob/a8933c619c9fe45dbda1263287ce2c46d5b42b1d/node/push_setup.sh#L2)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This is in the node dir, but this is only for a person to run?

Could we defensibly place node_k8s_setup.sh in epoxy-images also? https://github.com/m-lab/epoxy-images/tree/dev/actions/stage3_coreos
</blockquote></details>

I don't think it belongs there. The ePoxy action is not part of the image.

We would want to run this install script whenever `node_k8s_setup.sh` (the ePoxy action) changes, not whenever the stuff stored on the image changes. However, you are right that it should not have to be run by a human, and should instead be run by Travis and cause things to be pushed to sandbox, staging, and production in the ways we have come to expect. Adding a TODO and an issue.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/30#-:-LC4bhgh1yvSK1Bp6UFK:b-kvaiqr)*

**Comment by pboothe** [comment]
For the record, the added TODO was #30

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[node/push_setup.sh, line 2 at r1](https://reviewable.io/reviews/m-lab/k8s-support/30#-LC4G_q1EfoiVcKzKZ1k:-LC54qULAU49Ld04U7dA:bpii8ly) ([raw file](https://github.com/m-lab/k8s-support/blob/a8933c619c9fe45dbda1263287ce2c46d5b42b1d/node/push_setup.sh#L2)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

I don't think it belongs there. The ePoxy action is not part of the image.

We would want to run this install script whenever `node_k8s_setup.sh` (the ePoxy action) changes, not whenever the stuff stored on the image changes. However, you are right that it should not have to be run by a human, and should instead be run by Travis and cause things to be pushed to sandbox, staging, and production in the ways we have come to expect. Adding a TODO and an issue.
</blockquote></details>

I'm not sure I fully understand your concern.

My thought was that the action json files are currently stored in epoxy-images and published automatically to GCS on changes. If node_k8s_setup.sh was part of epoxy-images then it could be published to GCS automatically with any other changes to epoxy-images. This doesn't have to block this PR. My thought is that if we believe that most of the contents of `node_k8s_setup.sh` can eventually be converted into an epoxy action, then the functionality will end up in the epoxy-images repo. So, moving the script there too is not much different.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/30)*

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/30#-:-LC590_l9HH-U47qJ3SF:bnfp4nl)*

**Pull request merged**
