### PR TITLE
Incorporate local health checks from the HBS

### PR DESCRIPTION
**Pull request by cristinaleonr**
This change incorporates the health checks (port probing and k8s api calls) that the HBS runs to determine health.

It also adds a new `heartbeat-experiment` service account for experiments that use the HBS. This service account is necessary to be able to get pod and node information from the API server. It also incorporates the permissions from the [`kube-rbac-proxy`](https://github.com/m-lab/k8s-support/blob/main/k8s/roles/kube-rbac-proxy.jsonnet) service account, which the `ndt-virtual` deployments used to be bound to.

This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/723)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Thank you, @cristinaleonr - some requests for comments and one observation. None deal breaking. I'd like @nkinkade to also take a look.

@nkinkade Please also take a look at the service account changes here. I want to be sure that your mental model of the system includes these changes or if you see something I don't.

> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/723#-:-NAp9WB4AHSPxUZHHi08:b-4ouczh)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[`k8s/daemonsets/templates.jsonnet` line 388 at r1](https://reviewable.io/reviews/m-lab/k8s-support/723#-NAp9QOP8wBobwK9wYd-:-NAp9QOP8wBobwK9wYd0:b-5kb8es) ([raw file](https://github.com/m-lab/k8s-support/blob/8f908272276128eb650d8e7578779d435575cc2b/k8s/daemonsets/templates.jsonnet#L388)):*
> ```Jsonnet
>         '-prometheusx.listen-address=127.0.0.1:' + tcpPort
>       else
>         '-prometheusx.listen-address=$(PRIVATE_IP):' + tcpPort,
> ```

just observing: this is not localhost.
___
*[`k8s/roles/heartbeat-experiment.jsonnet` line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/723#-NAp8aF52NkorDmQ9ok3:-NAp8aF52NkorDmQ9ok4:b2cc6v0) ([raw file](https://github.com/m-lab/k8s-support/blob/8f908272276128eb650d8e7578779d435575cc2b/k8s/roles/heartbeat-experiment.jsonnet#L40)):*
> ```Jsonnet
>         ],
>         resources: [
>           'tokenreviews',
> ```

If I understand correctly, this SA role combines the permissions needed by both the HBS and kube-rbac-proxy ? 

I imagine that only the get/pods, get/nodes requests below are needed for HBS, and this tokenreviews and subjectacessreviews are needed by other parts of the system? Is it possible to add comments to these rules clarifying who needs them? I'm asking b/c role ACLs are complex and it could be easy to lose track of this in a future where we deploy components differently.

**Review by nkinkade — COMMENTED** [review]
The changes all LGTM.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/723#-:-NApVGMJ518sDNK7AVqd:bvqnhnu)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr and @stephen-soltesz)

___
*[`k8s/roles/heartbeat-experiment.jsonnet` line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/723#-NAp8aF52NkorDmQ9ok3:-NApVAR_60e0S21FTBj6:bk42q5e) ([raw file](https://github.com/m-lab/k8s-support/blob/8f908272276128eb650d8e7578779d435575cc2b/k8s/roles/heartbeat-experiment.jsonnet#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

If I understand correctly, this SA role combines the permissions needed by both the HBS and kube-rbac-proxy ? 

I imagine that only the get/pods, get/nodes requests below are needed for HBS, and this tokenreviews and subjectacessreviews are needed by other parts of the system? Is it possible to add comments to these rules clarifying who needs them? I'm asking b/c role ACLs are complex and it could be easy to lose track of this in a future where we deploy components differently.
</blockquote></details>

https://github.com/brancz/kube-rbac-proxy#how-does-it-work

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/723)* status: 0 of 1 approvals obtained (waiting on @cristinaleonr and @stephen-soltesz)

___
*[`k8s/roles/heartbeat-experiment.jsonnet` line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/723#-NAp8aF52NkorDmQ9ok3:-NApWmi0DUM7PpDld9_4:b-ovzbsg) ([raw file](https://github.com/m-lab/k8s-support/blob/8f908272276128eb650d8e7578779d435575cc2b/k8s/roles/heartbeat-experiment.jsonnet#L40)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

https://github.com/brancz/kube-rbac-proxy#how-does-it-work
</blockquote></details>

Yes, this SA role combines both permissions. I have added some comments.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: with comment character change.

> Reviewed 1 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/723#-:-NApZyfyDJwRMC1TkBjY:b-vzr1d1)* status: 0 of 1 approvals obtained

___
*[`k8s/daemonsets/templates.jsonnet` line 388 at r1](https://reviewable.io/reviews/m-lab/k8s-support/723#-NAp9QOP8wBobwK9wYd-:-NAp_NpuCX589bb4A2Ii:bcy18px) ([raw file](https://github.com/m-lab/k8s-support/blob/8f908272276128eb650d8e7578779d435575cc2b/k8s/daemonsets/templates.jsonnet#L388)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

just observing: this is not localhost.
</blockquote></details>

my mistake. this is only prometheus.
___
*[`k8s/roles/heartbeat-experiment.jsonnet` line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/723#-NAp8aF52NkorDmQ9ok3:-NApZqhiBbajmzpffDTY:b-e4mop8) ([raw file](https://github.com/m-lab/k8s-support/blob/8f908272276128eb650d8e7578779d435575cc2b/k8s/roles/heartbeat-experiment.jsonnet#L40)):*
<details><summary><i>Previously, cristinaleonr (Cristina Leon) wrote…</i></summary><blockquote>

Yes, this SA role combines both permissions. I have added some comments.
</blockquote></details>

Thank you. Please also use the `//` comment form.

I didn't realize jsonnet supported two comment characters. It should not imo. :)

**Review by cristinaleonr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/723)* status: 0 of 1 approvals obtained

___
*[`k8s/roles/heartbeat-experiment.jsonnet` line 40 at r1](https://reviewable.io/reviews/m-lab/k8s-support/723#-NAp8aF52NkorDmQ9ok3:-NApa40I7Mgw9V7FRb_2:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/8f908272276128eb650d8e7578779d435575cc2b/k8s/roles/heartbeat-experiment.jsonnet#L40)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you. Please also use the `//` comment form.

I didn't realize jsonnet supported two comment characters. It should not imo. :) 
</blockquote></details>

Done.

**Pull request merged**
