### PR TITLE
Configure nodeinfo v1.3.0 to use jostler

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/778)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Cool! looks good to me. I don't see the nodeinfo1 directory in pusher yet.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/778#-:-NQ0fiSd67qTWLbsXPd6:br2kyla)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
Sorry, I forget to use complete sentences sometimes. I don't see the nodeinfo1 data in the pusher-mlab-sandbox GCS bucket. That may be expected. 

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/778#-:-NQ0ipUe-flTmdKhN7Dz:bo8cgtl)* status: 0 of 1 approvals obtained

**Comment by SaiedKazemi** [comment]
@stephen-soltesz, I am working on getting the `jostler` container see the `/var/spool/datatypes` directory in the `nodeinfo` container.  Once this is done, we should see `nodeinfo1` in GCS.

**Comment by SaiedKazemi** [comment]
Closing this pull request in favor of https://github.com/m-lab/k8s-support/pull/779

**Pull request closed without merging**
