### PR TITLE
update conditional trc prod deployment

### PR DESCRIPTION
**Pull request by gfr10598**
This updates the prod deployment of trc to more or less match the staging deployment.

1. Use v0.8.2
2.  use scamper instead of scamper-daemon
3. Update other parameters to better match reality.     
      '-IPCacheTimeout=10m',  // Average trace latency is 4 minutes, 99th is 11 minutes, so this seems reasonable.
      '-IPCacheUpdatePeriod=1m', 
      '-scamper.timeout=30m',  // 99th percentile in staging is now 11 minutes, so 30 should give lots of headroom
      '-scamper.tracelb-W=15',

Will observe behavior in staging for a couple more hours, in addition to roughly last 24 hours (deployment took most of the day on Tuesday - all pods running 0.8.2 for about 16 hours so far.

Later today, we intend to tag for production deployment, after checking with soltesz or nkinkade.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/592)

### CODE REVIEW

**Review by SaiedKazemi — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/592)* status: 0 of 1 approvals obtained

**Comment by gfr10598** [comment]
Recreating this PR on a sandbox prefix branch.

**Comment by nkinkade** [comment]
@gfr10598, @SaiedKazemi): I suspect this PR is stale/abandoned. If so, would one of you please close it?

**Comment by SaiedKazemi** [comment]
@gfr10598 @nkinkade I am closing this PR because it's no longer needed.  All M-Lab platforms are running TRC v0.9.0.

**Pull request closed without merging**
