### PR TITLE
Updates k8s component versions in config + add documentation on upgrading

### PR DESCRIPTION
**Pull request by nkinkade**
This PR updates `k8s_deploy.conf` with upgrade version strings for core k8s components. It also adds some basic documentation on how to upgrade the API cluster in a project.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/590)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Added a few suggestions.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/590#-:-MdONCFS2h8su_LgIWWl:b-6jqsl1)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[README.md, line 65 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOG6Hz79eCW9U1bHIT:-MdOG6Hz79eCW9U1bHIU:bfgk4q3) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L65)):*
> ```Markdown
> breaking changes, then you will need to fix those before upgrading the cluster.
> Also pay attention to non-breaking changes, such as deprecations, which might
> not break the upgrade, but should nevertheless be addressed at some point.
> ```

maybe including something like: "... even if you don't address them now, consider creating an issue to note that they should be addressed in the near future."
___
*[README.md, line 68 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOGOZ-8tAjzSVuBxYs:-MdOGOZ02-HGb92cXo6A:bei7j8b) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L68)):*
> ```Markdown
> 
> Along with Kubernetes, during an upgrade we also update CNI plugins and crictl.
> The release pages for these components are these, respectively:
> ```

nit: please include a (possibly redundant) link to the kubernetes release pages in the list also. After doing this once, the main assist here will be making it easy to open all three release pages at once.
___
*[README.md, line 86 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOGmEYCXRz9thBUsSG:-MdOGmEYCXRz9thBUsSH:bw9ch7x) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L86)):*
> ```Markdown
> 
> ```
> K8S_VERSION
> ```

should these examples include sample versions? If these are only meant to enumerate the variables that need to be updated, perhaps a list?
___
*[README.md, line 99 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOMI4lAes_GQlmoUJF:-MdOMI4lAes_GQlmoUJG:b5ey28k) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L99)):*
> ```Markdown
> 
> That command should upgrade the entire API cluster for the specified GCP
> project. The script should be idempotent, and if it failes for some transitory
> ```

s/should be/is designed to be/
___
*[README.md, line 110 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOMRktAEhQKDeZTSmR:-MdOMRktAEhQKDeZTSmS:b-8pfu7r) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L110)):*
> ```Markdown
> 
> ```
> $ kubectl --context <project> get pods --all-namespaces | grep -v Running
> ```

I suggest including the `get nodes` command that you did on the VC before and after running the `upgrade_master_platform_cluster.sh` because this is also part of determining that the action succeeded.
___
*[README.md, line 114 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOMdik9loTlcl_XJz8:-MdOMdik9loTlcl_XJz9:b5tpgv6) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L114)):*
> ```Markdown
> 
> There should be no pods in a broken state that cannot be explained by some
> other known issue.
> ```

And, this can take a little while? I got the impression today that it may take a few minutes to stabilize.
___
*[README.md, line 122 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOMoKp69PCWEQJUdHv:-MdOMoKp69PCWEQJUdHw:b5ebt4g) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L122)):*
> ```Markdown
> problem isn't occuring. If something very subtle is wrong, then hopefully this
> extra time before hitting production will allow an mlab-staging alert to fire,
> or for someone to notice something is amiss.
> ```

Maybe include a hint about planning to update epoxy-images after this step. Ultimately, this README could link to a comparable section in epoxy-images for updating the versions, rebuilding, and initiating a rolling reboot? I guess the reboot is optional? Do we tend to prefer all k8s versions be the same?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/590)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[README.md, line 65 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOG6Hz79eCW9U1bHIT:-MdOVR595ZQe4xqMgt2T:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L65)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

maybe including something like: "... even if you don't address them now, consider creating an issue to note that they should be addressed in the near future."
</blockquote></details>

Done.
___
*[README.md, line 86 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOGmEYCXRz9thBUsSG:-MdOVbhe0wnPmTYZEHvs:b96cf0d) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L86)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

should these examples include sample versions? If these are only meant to enumerate the variables that need to be updated, perhaps a list?
</blockquote></details>

Changed to a list.
___
*[README.md, line 99 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOMI4lAes_GQlmoUJF:-MdOVmCh4a-IumHJD1V2:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L99)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/should be/is designed to be/
</blockquote></details>

Done.
___
*[README.md, line 110 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOMRktAEhQKDeZTSmR:-MdOWG-q8TKYp_K6D4ou:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L110)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I suggest including the `get nodes` command that you did on the VC before and after running the `upgrade_master_platform_cluster.sh` because this is also part of determining that the action succeeded.
</blockquote></details>

Done.
___
*[README.md, line 114 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOMdik9loTlcl_XJz8:-MdOWIsjDyFdi74o2cU-:b680vep) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L114)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

And, this can take a little while? I got the impression today that it may take a few minutes to stabilize.
</blockquote></details>

I don't think it should take a long time. Upgrading the API cluster should not affect workloads, I believe. I think what we saw this morning were rollouts in sandbox due to some other pushes, and the fact that both mlab1-lga0t and mlab3-lga0t were not booting, leaving all the pods in a broken state until I fixed the nodes a bit later.
___
*[README.md, line 122 at r1](https://reviewable.io/reviews/m-lab/k8s-support/590#-MdOMoKp69PCWEQJUdHv:-MdOYEgGD4F1RGfCa2zU:bfgtvn8) ([raw file](https://github.com/m-lab/k8s-support/blob/014cd026283eef3c40dd4a4dabc52d2189f89d35/README.md#L122)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Maybe include a hint about planning to update epoxy-images after this step. Ultimately, this README could link to a comparable section in epoxy-images for updating the versions, rebuilding, and initiating a rolling reboot? I guess the reboot is optional? Do we tend to prefer all k8s versions be the same?
</blockquote></details>

Done. I think a reboot is potentially optional, but it could take up to 60 days for the cluster to finally converge on a single version. I'm thinking that a rolling reboot is pretty safe, and probably preferable to waiting for all nodes to reboot themselves.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I believe I have addressed your comments. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/590#-:-MdOZrke36OLJn70vYjM:bcbpk2l)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

**Review by stephen-soltesz — APPROVED** [review]
:lgtm: -- thank you!

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/590#-:-MdOa_F31uopax5hCmaV:b-49kp4n)* status: 0 of 1 approvals obtained

**Pull request merged**
