### PR TITLE
Loads BBR module + configures fq qdisc

### PR DESCRIPTION
**Pull request by nkinkade**
Additionally, fixes a small bug in the IPv6 logic. We are currently grepping for the region of the sandbox control-place, not the region of the node.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/653)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/653#-:-Mwfi1j98LW4EHvWFnSp:bnfp4nl)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[manage-cluster/cloud-config_node.yml, line 57 at r1](https://reviewable.io/reviews/m-lab/k8s-support/653#-MwfhyeuDeOL4A6AOIoP:-MwfhyeuDeOL4A6AOIoQ:baot4zo) ([raw file](https://github.com/m-lab/k8s-support/blob/52a15aa2df2819d195eb2dd432c44a05b81beef9/manage-cluster/cloud-config_node.yml#L57)):*
> ```YAML
>     [Service]
>     Type=oneshot
>     ExecStart=tc qdisc replace dev ens4 root fq maxrate 10gbit
> ```

The device is always ens4?

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/653#-:-MwhoDqi9pmkCLLthu-m:b-e77fnf)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[manage-cluster/cloud-config_node.yml, line 57 at r1](https://reviewable.io/reviews/m-lab/k8s-support/653#-MwfhyeuDeOL4A6AOIoP:-MwhPElQAaDGCepbIiSf:bedy2ev) ([raw file](https://github.com/m-lab/k8s-support/blob/52a15aa2df2819d195eb2dd432c44a05b81beef9/manage-cluster/cloud-config_node.yml#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

The device is always ens4?
</blockquote></details>

It is on all the virtual nodes I've created so far. However, your comment prompted me to loop over all GCE VMs in sandbox and I found that quite a lot of them had `eth0` as the primary interface. I don't know how the name is determined, but I've added some changes to positively identify the device name and use that for configuring the fq qdisc on that device.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/653#-:-MwhpdPyCqYLFrw0XlYq:bnfp4nl)* status: 0 of 1 approvals obtained

___
*[manage-cluster/cloud-config_node.yml, line 57 at r1](https://reviewable.io/reviews/m-lab/k8s-support/653#-MwfhyeuDeOL4A6AOIoP:-MwhovmVEG-g8O47HcS6:b-3no1x6) ([raw file](https://github.com/m-lab/k8s-support/blob/52a15aa2df2819d195eb2dd432c44a05b81beef9/manage-cluster/cloud-config_node.yml#L57)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

It is on all the virtual nodes I've created so far. However, your comment prompted me to loop over all GCE VMs in sandbox and I found that quite a lot of them had `eth0` as the primary interface. I don't know how the name is determined, but I've added some changes to positively identify the device name and use that for configuring the fq qdisc on that device.
</blockquote></details>

Thank you for addressing the general case.

Seeing the code, I don't necessarily feel better now, hehe. :) 

Just thinking out loud: increasingly I'm wondering if small Go utilities could help keep configuration complexity lower and encapsulate the logic in a simple Go program (not for only this, but for the many small steps like those in manage-cluster/add_k8s_virtual_node.sh - the Compute API has Go bindings.)

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/653)* status: 0 of 1 approvals obtained

___
*[manage-cluster/cloud-config_node.yml, line 57 at r1](https://reviewable.io/reviews/m-lab/k8s-support/653#-MwfhyeuDeOL4A6AOIoP:-MwhqDK11uZcgYiI4TQn:b-ibuc8w) ([raw file](https://github.com/m-lab/k8s-support/blob/52a15aa2df2819d195eb2dd432c44a05b81beef9/manage-cluster/cloud-config_node.yml#L57)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for addressing the general case.

Seeing the code, I don't necessarily feel better now, hehe. :) 

Just thinking out loud: increasingly I'm wondering if small Go utilities could help keep configuration complexity lower and encapsulate the logic in a simple Go program (not for only this, but for the many small steps like those in manage-cluster/add_k8s_virtual_node.sh - the Compute API has Go bindings.)
</blockquote></details>

True, the shell scripting is pretty ugly. I've tested it and it does work, though. I'm surprised that there is no easier, more standardized way of determining the device name. You could be right that some sort of small utility to do this would be cleaner. However, it's not clear that it would be a general purpose utility, as this is the first time I can thing of that we've ever needed to know the device name in this sort of context. A Go utility could remove the need for the bit of shell scripting here, but the complexity would just be offloaded to the source for the Go utility itself.

**Pull request merged**
