### PR TITLE
Adds netstat collector to node_exporter

### PR DESCRIPTION
**Pull request by nkinkade**
The metrics provided by this collector could be useful, especially the ones related to SYN cookies, which may help us detect SYN floods.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/863)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
It looks like this adds about 40 metrics per machine. in production this would be about 40*400? 16k / minute.

I cannot count the total number of timeseries in the production instance `count({__name__=~".+"})` b/c the query times out. So, I do not know what percentage of total metrics this represents.

I recommend monitoring the prometheus instance (via Prometheus Self monitoring dashboard) after production juts to make sure nothing is overloaded.

:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/863#-:-Nm2FTVJ0cfTJnfd0rQB:b-ga3w0m)* status: 0 of 1 approvals obtained

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: Alternatively, we could just not enable this collector. There are no current dashboards or alerts that use any metric from it, of course. Enabling it is more or less speculative at this point, in the hope that it  _might_ be useful at some point to help diagnose situations like we have in ORD. What do you think?

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/863#-:-Nm2UlY76eBCaU0M2nSc:bxw6tp5)* status: 0 of 1 approvals obtained

**Review by stephen-soltesz — COMMENTED** [review]
Oh, I don't object to adding it. My concern is adjacent - we want to be able to measure the impact of large new metric additions. In this case, I noticed that it's hard to compare how much of an increase this represents in production.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/863#-:-Nm2fqZf-WH0GhwZrlOV:b-wnpgu)* status: 0 of 1 approvals obtained

**Comment by stephen-soltesz** [comment]
Sorry - did I accidentally stall this PR?

**Comment by nkinkade** [comment]
I must have closed this PR accidentally. In any case, it was stalled and the metrics provided by the `netstat` collector were perhaps not even going to help us for the case in which it was proposed in the first place (SYN floods). Maybe let's just leave it closed?

**Pull request closed without merging**
