### PR TITLE
Removes token_server code

### PR DESCRIPTION
**Pull request by nkinkade**
This, I believe, should be the last piece to resolve https://github.com/m-lab/k8s-support/issues/504.

The token_server code [has already been migrated to the epoxy-extensions repository](https://github.com/m-lab/epoxy-extensions/pull/5), and [Docker Hub builds for epoxy-extensions](https://hub.docker.com/repository/docker/measurementlab/epoxy-extensions/tags?page=1&ordering=last_updated) have been configured to build both the `bmc-store-password` and `token_server` extensions.

This PR removes the token_server code from this repository, and also modifies the API server cloud-init configuration to fetch the extension image from the new Docker Hub repository.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/530)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/530#-:-MQJMQcm6o12Do1wx46B:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[manage-cluster/cloud-config_master.yml, line 30 at r1](https://reviewable.io/reviews/m-lab/k8s-support/530#-MQJM7jE3UxixnkVGKSa:-MQJM7jE3UxixnkVGKSb:b-4wpkww) ([raw file](https://github.com/m-lab/k8s-support/blob/05650b4821954e5999187e42a611600509cab485/manage-cluster/cloud-config_master.yml#L30)):*
> ```YAML
>                                   --volume /:/ro:ro \
>                                   --name %N -- \
>                                   measurementlab/epoxy-extensions:token_server-v0.2.0 \
> ```

this is a nitty-nit-nit. I recommend that we adopt one convention for the extension tag names allowing either only dashes "-" or underscores for the service (for example to match the binary name). this is not blocking. and it's so nitty that I feel a little bad saying anything.

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/530)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[manage-cluster/cloud-config_master.yml, line 30 at r1](https://reviewable.io/reviews/m-lab/k8s-support/530#-MQJM7jE3UxixnkVGKSa:-MQJN5ia7osykU9UdbCe:bbe1mdd) ([raw file](https://github.com/m-lab/k8s-support/blob/05650b4821954e5999187e42a611600509cab485/manage-cluster/cloud-config_master.yml#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

this is a nitty-nit-nit. I recommend that we adopt one convention for the extension tag names allowing either only dashes "-" or underscores for the service (for example to match the binary name). this is not blocking. and it's so nitty that I feel a little bad saying anything.
</blockquote></details>

Believe it or not, I actually anticipated you calling this out. :)  And it's an inconsistency I'm not 100% happy with either, so you are not at all wrong to mention it. There were previously (still maybe are) some inconsistency with the naming of token_server things. For example, [the Docker Hub repo was named `k8s-token-server`](https://hub.docker.com/repository/docker/measurementlab/k8s-token-server/). And the systemd unit on the masters [was likewise named `token-server`](https://github.com/m-lab/k8s-support/blob/08c9582056e0ecefce8a5da0dc678ad2657a3888/manage-cluster/cloud-config_master.yml#L5). Additionally, [all GCP resources related to the `token_server` have a "basename" of `token-server`](https://github.com/m-lab/k8s-support/blob/master/manage-cluster/k8s_deploy.conf#L48), with a dash. 

When I was initially developing the `bmc-store-password` extension, I chose to use dashes, for no other reason than it looked better to me, and it wasn't until after the extension was pretty much complete that I realized that the `token_server` extension was using underscores in many places.

When I went to enable the `bmc-store-password` extension in ePoxy I found that the extension's operation name in ePoxy is `allocate_k8s_token`, with underscores and a name completely different than the extension's name in code, so I changed the extension name in ePoxy to `bmc_store_password`, also with underscores.  Now what we have a terrible mix of dashes and underscores all of the place that would take some time to undo.... completely doable, but maybe not worth the effort at the moment?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/530)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[manage-cluster/cloud-config_master.yml, line 30 at r1](https://reviewable.io/reviews/m-lab/k8s-support/530#-MQJM7jE3UxixnkVGKSa:-MQJlIUVDmIzl3BafP4H:b-oz1562) ([raw file](https://github.com/m-lab/k8s-support/blob/05650b4821954e5999187e42a611600509cab485/manage-cluster/cloud-config_master.yml#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Ah, since these are all parts of the epoxy-extensions repo, and b/c ePoxy only supports extension names with underscores, is this the answer to the question?
</blockquote></details>

And, in general, I'm more concerned with having an answer to the question for the next time we have to name something than retroactively changing things (unless the current state invites confusion or translation or special handling code).

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/530)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[manage-cluster/cloud-config_master.yml, line 30 at r1](https://reviewable.io/reviews/m-lab/k8s-support/530#-MQJM7jE3UxixnkVGKSa:-MQJlYNK4ZDiDtYiDUyf:b-cgn42h) ([raw file](https://github.com/m-lab/k8s-support/blob/05650b4821954e5999187e42a611600509cab485/manage-cluster/cloud-config_master.yml#L30)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

And, in general, I'm more concerned with having an answer to the question for the next time we have to name something than retroactively changing things (unless the current state invites confusion or translation or special handling code).
</blockquote></details>

Perhaps. I'll submit another couple PRs to make this cleaner.

**Comment by nkinkade** [comment]
I'd like to correct this now, since it is easy and it is at the top of my mind. This is another one of those cases of gradually increasing tech debt or entropy that seems small now, but later on one finds that a lot of tiny inconsistencies like this have added up into a big confusion.

**Pull request merged**
