### PR TITLE
Drops all unneeded capabilities for containers + updates README

### PR DESCRIPTION
**Pull request by nkinkade**
This is a redux of #816, the branch of which I accidentally overwrote before the PR had been reviewed. Github now (always?) has some feature to restore branches, and that is what this is.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/820)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/820)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`README.md` line 138 at r1](https://reviewable.io/reviews/m-lab/k8s-support/820#-NZ7DGO2Bom17m8D5Pyw:-NZ7DGO2Bom17m8D5Pyx:bzcl402) ([raw file](https://github.com/m-lab/k8s-support/blob/9a3af779e449384a69aae5e349d6c69fe85275dc/README.md#L138)):*
> ```Markdown
> cause them to boot with the upgraded versions of Kubernetes components.
> 
> # Running containers as non-root
> ```

I recommend installing https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint in VSCode.

What does it say about these headers and spacing?
___
*[`README.md` line 148 at r1](https://reviewable.io/reviews/m-lab/k8s-support/820#-NZ7Data0Dp1se6eIb6G:-NZ7Data0Dp1se6eIb6H:b1003rr) ([raw file](https://github.com/m-lab/k8s-support/blob/9a3af779e449384a69aae5e349d6c69fe85275dc/README.md#L148)):*
> ```Markdown
> filesystem attributes that the kernel reads when a binary is executed.
> 
> ```
> ```

Would you be willing to split these by category? For example: measurement services (e.g. dash, disco, heartbeat, msak, etc.), system services, and other?

In particular, I'm hoping that the measurement service section can serve as a reference for future services about what to include or not or at least what is typical and possible.
___
*[`k8s/daemonsets/experiments/msak.jsonnet` line 103 at r1](https://reviewable.io/reviews/m-lab/k8s-support/820#-NZ7ETum7NkW0akNxXXD:-NZ7ETum7NkW0akNxXXE:b-xe0lf) ([raw file](https://github.com/m-lab/k8s-support/blob/4b8e1b9019dd1328a277d79cf04320402aeb89f2/k8s/daemonsets/experiments/msak.jsonnet#L103)):*
> ```Jsonnet
>             ],
>           },
>           {
> ```

Thank you for this.

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: I believe I have addressed your concerns. PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/820#-:-NZCz2yB1gUIKFh_DRJv:baey5um)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`README.md` line 138 at r1](https://reviewable.io/reviews/m-lab/k8s-support/820#-NZ7DGO2Bom17m8D5Pyw:-NZCxFYD0O-XENJHLEQl:bkicf9i) ([raw file](https://github.com/m-lab/k8s-support/blob/9a3af779e449384a69aae5e349d6c69fe85275dc/README.md#L138)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I recommend installing https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint in VSCode.

What does it say about these headers and spacing?
</blockquote></details>

I have this extension installed, but didn't make this edit in vscode. I opened it in vscode and it recommended to add a  blank like below headings, which I have now done.
___
*[`README.md` line 148 at r1](https://reviewable.io/reviews/m-lab/k8s-support/820#-NZ7Data0Dp1se6eIb6G:-NZCyKWc7PvWB5KBe-9F:b-x19vxi) ([raw file](https://github.com/m-lab/k8s-support/blob/9a3af779e449384a69aae5e349d6c69fe85275dc/README.md#L148)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Would you be willing to split these by category? For example: measurement services (e.g. dash, disco, heartbeat, msak, etc.), system services, and other?

In particular, I'm hoping that the measurement service section can serve as a reference for future services about what to include or not or at least what is typical and possible.
</blockquote></details>

Done. I broke them into 3 categories:

* Measurement services
* Sidecar services
* System services

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/820#-:-NZD0Q5a2vmIcaA1M7kB:bnfp4nl)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`README.md` line 148 at r1](https://reviewable.io/reviews/m-lab/k8s-support/820#-NZ7Data0Dp1se6eIb6G:-NZD0IibBkzk0hdtlcsc:b-9755fn) ([raw file](https://github.com/m-lab/k8s-support/blob/9a3af779e449384a69aae5e349d6c69fe85275dc/README.md#L148)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Done. I broke them into 3 categories:

* Measurement services
* Sidecar services
* System services
</blockquote></details>

Thank you!
___
*[`README.md` line 39 at r2](https://reviewable.io/reviews/m-lab/k8s-support/820#-NZD02qPBF6pr7bs2Thm:-NZD02qPBF6pr7bs2Thn:bkzh3qi) ([raw file](https://github.com/m-lab/k8s-support/blob/2041fff0a1981180d3aa39c40c47806ec038039f/README.md#L39)):*
> ```Markdown
> To deploy NDT pod:
> 
> 1. Check <https://grafana.mlab-staging.measurementlab.net/d/K8-zAIuik/k8s-master-cluster?orgId=1&var-datasource=k8s%20platform%20(mlab-staging)&var-master=All>
> ```

Just confirming: this is meant to be "staging"?

**Review by nkinkade — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/820)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`README.md` line 39 at r2](https://reviewable.io/reviews/m-lab/k8s-support/820#-NZD02qPBF6pr7bs2Thm:-NZD0z5DBOu3cN5jc5Qr:b-jxtq5d) ([raw file](https://github.com/m-lab/k8s-support/blob/2041fff0a1981180d3aa39c40c47806ec038039f/README.md#L39)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Just confirming: this is meant to be "staging"?
</blockquote></details>

I don't think it should be staging, but that entire dashboard is broken at the moment because the API machines changed names when I brought them under TF control. Indeed, this entire document is so out of date that it needs to be completely overhauled, or to just wholesale delete large portions of it. Since this line wasn't part of the changes I was making, and all of it is wrong anyway, I'm going to leave it for now... for a larger clean up PR.

**Comment by stephen-soltesz** [comment]
Part of:
* https://github.com/m-lab/ops-tracker/issues/1650

**Pull request merged**
