### PR TITLE
Updated the system to use git-hooks

### PR DESCRIPTION
**Pull request by pboothe**
Updated all shell scripts to pass the linter.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/19)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---

*[cloud/setup_cloud_k8s_master.sh, line 20 at r1](https://reviewable.io/reviews/m-lab/k8s-support/19#-LAy_MEmCWpmjbEUiPlo:-LAy_MEmCWpmjbEUiPlp:b-gpkmpb) ([raw file](https://github.com/m-lab/k8s-support/blob/2a24977567cd829fe81564f689911b943b0d9186/cloud/setup_cloud_k8s_master.sh#L20)):*
> ```Shell
> 
> # Add gcloud to PATH.
> # Tell the linter not to worry about that file.
> ```

This comment isn't clear to me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/19)*

**Comment by gfr10598** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/19)*

**Comment by pboothe** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[cloud/setup_cloud_k8s_master.sh, line 20 at r1](https://reviewable.io/reviews/m-lab/k8s-support/19#-LAy_MEmCWpmjbEUiPlo:-LAyaKO1-sj1TWNoY8J8:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/2a24977567cd829fe81564f689911b943b0d9186/cloud/setup_cloud_k8s_master.sh#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This comment isn't clear to me.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/19)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/19#-:-LAyaSgj-bUiXivVb7wk:bnfp4nl)*

**Comment by gfr10598** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/19)*

**Pull request merged**
