### PR TITLE
Configure jostler to upload autoloaded datatypes

### PR DESCRIPTION
**Pull request by SaiedKazemi**
This commit adds jostler (https://github.com/m-lab/jostler) configuration to this repo.

Changes were tested as follows:

$ MSAK=k8s/daemonsets/experiments/msak.jsonnet
$ jsonnet-lint $MSAK
$ jsonnet --ext-str PROJECT_ID=mlab-sandbox $MSAK

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/769)

### CODE REVIEW

**Review by stephen-soltesz — COMMENTED** [review]
Thanks, this is great.

One minor comment. I'd like to see the configuration working in sandbox before I approve.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/769#-:-NOFaeyq1vu_yoV3A88_:bbgubs5)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`k8s/daemonsets/templates.jsonnet` line 329 at r1](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOFYZULD6chrcXJRVge:-NOFYZULD6chrcXJRVgf:b-fcguq8) ([raw file](https://github.com/m-lab/k8s-support/blob/5fb088038ec753b08d751390e43007e16670345e/k8s/daemonsets/templates.jsonnet#L329)):*
> ```Jsonnet
> ;
> 
> local Jostler(expName, tcpPort, datatypes_autoloaded, hostNetwork, bucket) = [
> ```

for style consistency, please use a camel case variable for `datatypes_autoloaded`.

**Review by nkinkade — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/769)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi)

___
*[`k8s/daemonsets/README.md` line 59 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPQ-Zu0VKasIhbcSep:-NOPQ-Zu0VKasIhbcSeq:blwa5rt) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/README.md#L59)):*
> ```Markdown
> 
> Note: The `utilization` service assigns port 9989 to `pusher` (see
> k8s/daemonsets/core/utilization.jsonnet).
> ```

I think this note can be removed. The "utility-support" service has not been used in years. Indeed, the DaemonSet manifest you reference should be removed from the repository, and it is only an oversight that it is still there. Only the DaemonSets referenced in system.jsonnet are deployed: https://github.com/m-lab/k8s-support/blob/main/system.jsonnet#L12
___
*[`k8s/daemonsets/templates.jsonnet` line 331 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPSas6EekAqXLJ5Qkz:-NOPSas6EekAqXLJ5Ql-:bfg3fjk) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L331)):*
> ```Jsonnet
> local Jostler(expName, tcpPort, datatypesAutoloaded, hostNetwork, bucket) = [
>   {
>     local version='v1.0.1',
> ```

This variable is only referenced once two lines below. Would it be simpler to just remove the variable and reference the version directly in the `image:` line? Other side-cars do things this way. Pusher is an exception because it references the variable 3 or so times in the arguments.
___
*[`k8s/daemonsets/templates.jsonnet` line 335 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPR5hf9fA3HSpC_6i5:-NOPR5hf9fA3HSpC_6i6:b-70ik0u) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L335)):*
> ```Jsonnet
>     image: 'measurementlab/jostler:'+version,
>     args: [
>       // TODO: Add the following commented-out lines when Prometheus support
> ```

Just to be sure, does this mean that Jostler currently does not implement a metrics endpoint on some certain port, and that it exports no metrics yet? If yes, then fair enough, but  if not then I believe this should be uncommented now.
___
*[`k8s/daemonsets/templates.jsonnet` line 355 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPTFmfBM5tne-WRqR4:-NOPTFmfBM5tne-WRqR5:blujc6t) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L355)):*
> ```Jsonnet
>       {
>         name: 'GOOGLE_APPLICATION_CREDENTIALS',
>         value: '/etc/credentials/pusher.json', // jostler uses pusher's credentials
> ```

This is maybe okay as a workaround for now in sandbox, but longer term I think jostler should have its own service account and credentials. This will avoid confusing name disparities down the line, which are easy for us to decipher today but may be hard to understand in the future.
___
*[`k8s/daemonsets/templates.jsonnet` line 555 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPWIdH-AHUsEQi2VKC:-NOPWIdH-AHUsEQi2VKD:bzbttci) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L555)):*
> ```Jsonnet
> };
> 
> local ExperimentNoIndex(name, bucket, anonMode, datatypes, datatypesAutoloaded, hostNetwork, siteType='physical') = {
> ```

A question for myself, to help bring me up to speed on jostler. Is jostler envisioned as a complete, drop-in replacement for pusher, for all datatypes. Or is jostler only ever going to handle autoloaded datatypes. Or is it that jostler today only handles autoloaded datatypes, but in the future will handle all datatypes, autoloaded or not?  

I ask because this distinction between `datatypes` and `datatypesAutoloaded`, and `allDatatypes` and `allVolumes` is rather confusing to sort through. It seems like it could be a cleaner transition for jostler to receive a list of all datatypes (like pusher does today), and could be configured (maybe via a provisional flag) to operate on a select subset of the datatypes, until it fully supports everything.

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/templates.jsonnet` line 335 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPR5hf9fA3HSpC_6i5:-NOPZ4hEBpM-kwPvBlkj:b-w36x8z) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L335)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Just to be sure, does this mean that Jostler currently does not implement a metrics endpoint on some certain port, and that it exports no metrics yet? If yes, then fair enough, but  if not then I believe this should be uncommented now.
</blockquote></details>

Yes, jostler does not implement any metrics yet.  As soon as it does, I will uncomment these lines.

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/templates.jsonnet` line 355 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPTFmfBM5tne-WRqR4:-NOPZpLn3im6tYTuoj-v:b-bw052b) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L355)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This is maybe okay as a workaround for now in sandbox, but longer term I think jostler should have its own service account and credentials. This will avoid confusing name disparities down the line, which are easy for us to decipher today but may be hard to understand in the future.
</blockquote></details>

I was leaning towards having separate credentials for `jostler` but because `jostler` uploads to `pusher` buckets, @soltes suggested that we use the same credentials.  I think we should discuss the pros and cons of each option offline because I'd like to add it to the design doc.

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/templates.jsonnet` line 555 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPWIdH-AHUsEQi2VKC:-NOPaT5O6-I0CqNrUfGg:bmzrakf) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L555)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

A question for myself, to help bring me up to speed on jostler. Is jostler envisioned as a complete, drop-in replacement for pusher, for all datatypes. Or is jostler only ever going to handle autoloaded datatypes. Or is it that jostler today only handles autoloaded datatypes, but in the future will handle all datatypes, autoloaded or not?  

I ask because this distinction between `datatypes` and `datatypesAutoloaded`, and `allDatatypes` and `allVolumes` is rather confusing to sort through. It seems like it could be a cleaner transition for jostler to receive a list of all datatypes (like pusher does today), and could be configured (maybe via a provisional flag) to operate on a select subset of the datatypes, until it fully supports everything. 
</blockquote></details>

`jostler` is not a drop-in replacement for `pusher`.  You may want to read its design doc (https://docs.google.com/document/d/1kJ2oy5MAwYBBCq2mVOoJBjq4zU2xiEy1gRAYNoim920/edit#heading=h.41av68dw9f5v) for its motivation and differences with `pusher`.

Regarding variable names `datatypes`, `datatypesAutoloaded`, etc., I tried to make the absolute minimum changes but these variable names can be changed with any suggestions you may have.

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/README.md` line 59 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPQ-Zu0VKasIhbcSep:-NOPYIlG1LfYkNmKX5DO:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/README.md#L59)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I think this note can be removed. The "utility-support" service has not been used in years. Indeed, the DaemonSet manifest you reference should be removed from the repository, and it is only an oversight that it is still there. Only the DaemonSets referenced in system.jsonnet are deployed: https://github.com/m-lab/k8s-support/blob/main/system.jsonnet#L12
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/templates.jsonnet` line 329 at r1](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOFYZULD6chrcXJRVge:-NOPYL4d-RRwcX9ny44Z:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/5fb088038ec753b08d751390e43007e16670345e/k8s/daemonsets/templates.jsonnet#L329)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

for style consistency, please use a camel case variable for `datatypes_autoloaded`.
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/templates.jsonnet` line 331 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPSas6EekAqXLJ5Qkz:-NOPYxUh-n7co6k0tXU7:b-896fix) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L331)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This variable is only referenced once two lines below. Would it be simpler to just remove the variable and reference the version directly in the `image:` line? Other side-cars do things this way. Pusher is an exception because it references the variable 3 or so times in the arguments.
</blockquote></details>

Done.

**Review by nkinkade — APPROVED** [review]
@SaiedKazemi: :lgtm:, with one small question about uncommenting the prometheus  parts now as opposed to later, at your discretion.

> Reviewed 8 of 11 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/769#-:-NOQLEB_BMsZHomMRIzE:bd8x1xc)* status: 0 of 1 approvals obtained (waiting on @SaiedKazemi, @soltes, and @stephen-soltesz)

___
*[`k8s/daemonsets/templates.jsonnet` line 335 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPR5hf9fA3HSpC_6i5:-NOQ2WKpE9ofBt7HKDMG:bo1xoev) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L335)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Yes, jostler does not implement any metrics yet.  As soon as it does, I will uncomment these lines.
</blockquote></details>

Is there any harm in uncommenting this now?
___
*[`k8s/daemonsets/templates.jsonnet` line 355 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPTFmfBM5tne-WRqR4:-NOQ2wM852p_IrpLNTpq:b-31kpq3) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L355)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

I was leaning towards having separate credentials for `jostler` but because `jostler` uploads to `pusher` buckets, @soltes suggested that we use the same credentials.  I think we should discuss the pros and cons of each option offline because I'd like to add it to the design doc.
</blockquote></details>

I think I would tend to agree with you that jostler should have its own service account and credentials. The service account can be given the exact same permissions/roles as pusher on the exact same bucket. When the day comes that we jostler fully replaces pusher, we can then safely delete the pusher service account with no adverse consequences. But, as I mentioned, I think piggy-backing on pusher's service account is probably okay for this initial testing and deployment.

Let's proceed as is, and we can revisit this later.
___
*[`k8s/daemonsets/templates.jsonnet` line 555 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPWIdH-AHUsEQi2VKC:-NOQ56dY5hH_-2r1ieCO:b-xdl1za) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L555)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

`jostler` is not a drop-in replacement for `pusher`.  You may want to read its design doc (https://docs.google.com/document/d/1kJ2oy5MAwYBBCq2mVOoJBjq4zU2xiEy1gRAYNoim920/edit#heading=h.41av68dw9f5v) for its motivation and differences with `pusher`.

Regarding variable names `datatypes`, `datatypesAutoloaded`, etc., I tried to make the absolute minimum changes but these variable names can be changed with any suggestions you may have.
</blockquote></details>

Got it. Jostler will only ever handle archives that can be autoloaded, and will coexist with pusher in all experiment pods for the foreseeable future.

**Comment by SaiedKazemi** [comment]
Thank you for your review.

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/templates.jsonnet` line 335 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPR5hf9fA3HSpC_6i5:-NOTfmix0SwXcWCulyOJ:bcr026l) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L335)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is there any harm in uncommenting this now?
</blockquote></details>

Because the `-prometheusx.listen-address` flag is not defined yet, it causes `jostler` to abort:
```
flag provided but not defined: -prometheusx.listen-address
```

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/templates.jsonnet` line 355 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPTFmfBM5tne-WRqR4:-NOTgcbf63aL4hqEdNSU:brxp9sq) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L355)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I think I would tend to agree with you that jostler should have its own service account and credentials. The service account can be given the exact same permissions/roles as pusher on the exact same bucket. When the day comes that we jostler fully replaces pusher, we can then safely delete the pusher service account with no adverse consequences. But, as I mentioned, I think piggy-backing on pusher's service account is probably okay for this initial testing and deployment.

Let's proceed as is, and we can revisit this later.
</blockquote></details>

Sounds good.

**Comment by SaiedKazemi** [comment]
*[`k8s/daemonsets/templates.jsonnet` line 555 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPWIdH-AHUsEQi2VKC:-NOTgiqD90qRn5wijeg4:bp8eu3) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L555)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Got it. Jostler will only ever handle archives that can be autoloaded, and will coexist with pusher in all experiment pods for the foreseeable future.
</blockquote></details>

Yes, that's correct.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/769)* status: 0 of 1 approvals obtained (waiting on @nkinkade and @soltes)

___
*[`k8s/daemonsets/templates.jsonnet` line 355 at r3](https://reviewable.io/reviews/m-lab/k8s-support/769#-NOPTFmfBM5tne-WRqR4:-NOoWgF231yhc3QOqi4d:b-5wt87p) ([raw file](https://github.com/m-lab/k8s-support/blob/13df26b283fef858d5c63f283eb809d5d8fbb0ab/k8s/daemonsets/templates.jsonnet#L355)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

To clarify my position here (which I didn't do adequately in person).

In principle, I support separate credentials for separate services. I do not recommend that any of us spend time manually managing these credentials until we have automated support via terraform for provisioning these credentials.

Perhaps I should have recommended a `TODO()` here, to separate credentials once automated provisioning of SA's are supported.

**Comment by SaiedKazemi** [comment]
@stephen-soltesz Thanks for clarifying.  It makes sense and I agree with you.

**Pull request merged**
