### PR TITLE
Adds support for MultiNetworkPolicy definitions

### PR DESCRIPTION
**Pull request by nkinkade**
This PR deploys the multi-networkpolicy DaemonSet, which reads in a set of MultiNetworkPolicy objects and enforces them via iptables rules in each pod. A MultiNetworkPolicy is almost identical to the [native k8s NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/), with a couple of very small differences. MultiNetworkPolicies are designed to work in conjunction with the `multus` CNI plugin and NetworkAttachmentDefinitions. The multi-networkpolicy DaemonSet will apply a certain MultiNetworkPolicy to any pod with an annotation that matches the NetworkAttachmentDefinition specified in the `'k8s.v1.cni.cncf.io/policy-for` annotation of the MultiNetworkPolicy.

More infomation:

https://github.com/k8snetworkplumbingwg/multi-networkpolicy
https://github.com/k8snetworkplumbingwg/multi-networkpolicy-iptables

multi-networkpolicy-iptables does not yet support the v1beta2  API version, which added support for the `endPort` field in a port specification, which allows you to define a port range. We require this functionality to support ndt5 testing on ephemeral ports. I forked the repository and made the changes necessary to support v1beta2:

https://github.com/k8snetworkplumbingwg/multi-networkpolicy-iptables/compare/master...m-lab:multi-networkpolicy-iptables:v1beta2

The changes seems to work, though I have not yet tried to add any unit tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/907)

### CODE REVIEW

**Review by nkinkade — COMMENTED** [review]
@stephen-soltesz: PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/907#-:-O8n8QXl4JcfCIr3dG97:b-e77fnf)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`config/multi-networkpolicy.jsonnet` line 13 at r1](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8cGG-fDysx3OjbNxJC:-O8cig2wBlJ6UGgISSXz:bake4uc) ([raw file](https://github.com/m-lab/k8s-support/blob/64b4d5f5791288c3313375513740508894ade895/config/multi-networkpolicy.jsonnet#L13)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm imagining these are really important commands for the network policy to work as intended.

Please use `|||` for multiline, inline text so the content/script commands are easier to read.
</blockquote></details>

They actually aren't important, or even used. The custom rules are not applied unless you pass special flags to multi-networkpolicy:

```
--custom-v4-igress-rule-file
--custom-v4-egress-rule-file
--custom-v6-igress-rule-file
--custom-v4-egress-rule-file
```

I removed the sample rules, expanded the ConfigMap data section, and added a comment about how to use them. Even though they are unused I left the ConfigMap in place just to facilitate adding custom rules in the future.
___
*[`k8s/custom-resource-definitions/multi-networkpolicy.jsonnet` line 1 at r1](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8cGWwG2B9FDxxIZKPH:-O8cjqvP9ULZTCZ9NbSu:b-e777x8) ([raw file](https://github.com/m-lab/k8s-support/blob/64b4d5f5791288c3313375513740508894ade895/k8s/custom-resource-definitions/multi-networkpolicy.jsonnet#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

You said this was essentially copied from an upstream source unmodified?

Was any part modified?
</blockquote></details>

The only change I made was this:

```
--- scheme.yml	2024-10-07 14:50:42.090879884 -0600
+++ scheme.yml.new	2024-10-07 14:51:22.596794739 -0600
@@ -15,7 +15,7 @@
   versions:
     - name: v1beta1
       served: true
-      storage: true
+      storage: false
       schema:
         openAPIV3Schema:
           description: "MultiNetworkPolicy is a CRD schema to provide NetworkPolicy
@@ -454,8 +454,8 @@
               type: object
           type: object
     - name: v1beta2
-      served: false
-      storage: false
+      served: true
+      storage: true
       schema:
         openAPIV3Schema:
           description: "MultiNetworkPolicy is a CRD schema to provide NetworkPolicy
```

... basically to enable v1beta2, and make it the default stored version.
___
*[`k8s/networkpolicies/msak.jsonnet` line 1 at r1](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8cEtyQ6jBloZghSQb4:-O8n1jwn7ECsCTsIVsIu:b-du89c6) ([raw file](https://github.com/m-lab/k8s-support/blob/64b4d5f5791288c3313375513740508894ade895/k8s/networkpolicies/msak.jsonnet#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since these network policies are so tightly related to the service configuration, is there a way we can imagine this being integrated into the k8s/daemonsets/experiments configs? Otherwise, it could be confusing updating the service but not knowing about or forgetting the network policy to allow a new port. Also, these aren't expected to change often so this could be long term rather than short term priority.

I could imagine this two ways. One is just an inline declaration like this. Second, it could be added as part of the `Experiment` template that passes a set of parameters to the relevant MultiNetworkPolicy object.
</blockquote></details>

I added a new MultiNetworkPolicy template to templates.jsonnet, and in each experiment manifest there is now a `ports` variable that gets passed to the call to the new template. The experiment jsonnet files now contain both the DaemonSet definition and the experiment's corresponding MultiNetworkPolicy. Does this satisfy your concern? The two things are now more tightly coupled and configured in the same file.

**Review by stephen-soltesz — COMMENTED** [review]
This is great. I think this looks good to me. What else is merging conditional on?

> Reviewed 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/907#-:-O8nDXs5D0H4FECiJ98v:b-hdvgpt)* status: 0 of 1 approvals obtained (waiting on @nkinkade)

___
*[`k8s/custom-resource-definitions/multi-networkpolicy.jsonnet` line 1 at r1](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8cGWwG2B9FDxxIZKPH:-O8nA6xqA15HBYOBi2ST:b-9755fn) ([raw file](https://github.com/m-lab/k8s-support/blob/64b4d5f5791288c3313375513740508894ade895/k8s/custom-resource-definitions/multi-networkpolicy.jsonnet#L1)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

The only change I made was this:

```
--- scheme.yml	2024-10-07 14:50:42.090879884 -0600
+++ scheme.yml.new	2024-10-07 14:51:22.596794739 -0600
@@ -15,7 +15,7 @@
   versions:
     - name: v1beta1
       served: true
-      storage: true
+      storage: false
       schema:
         openAPIV3Schema:
           description: "MultiNetworkPolicy is a CRD schema to provide NetworkPolicy
@@ -454,8 +454,8 @@
               type: object
           type: object
     - name: v1beta2
-      served: false
-      storage: false
+      served: true
+      storage: true
       schema:
         openAPIV3Schema:
           description: "MultiNetworkPolicy is a CRD schema to provide NetworkPolicy
```

... basically to enable v1beta2, and make it the default stored version.
</blockquote></details>

Thank you!
___
*[`k8s/daemonsets/core/multi-networkpolicy.jsonnet` line 50 at r2](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8nC-If-BYeUnxF_UD1:-O8nC-If-BYeUnxF_UD2:b-1xja85) ([raw file](https://github.com/m-lab/k8s-support/blob/bdf364cc5ce701511bb94c4fdb3006edb82a3bb1/k8s/daemonsets/core/multi-networkpolicy.jsonnet#L50)):*
> ```Jsonnet
>               '/usr/bin/multi-networkpolicy-iptables',
>             ],
>             args: [
> ```

Clarifying: this is where someone might add `--custom-v4-igress-rule-file` and the others? If so, please make that explicit. The earlier file mentions "flags to multi-networkpolicy" and I see this is "multi-networkpolicy-iptables". If it's not this, where are the "multi-networkpolicy" flags?
___
*[`k8s/networkpolicies/msak.jsonnet` line 1 at r1](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8cEtyQ6jBloZghSQb4:-O8nD-vLEmDPYDS-jPA1:b9znln1) ([raw file](https://github.com/m-lab/k8s-support/blob/64b4d5f5791288c3313375513740508894ade895/k8s/networkpolicies/msak.jsonnet#L1)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

I added a new MultiNetworkPolicy template to templates.jsonnet, and in each experiment manifest there is now a `ports` variable that gets passed to the call to the new template. The experiment jsonnet files now contain both the DaemonSet definition and the experiment's corresponding MultiNetworkPolicy. Does this satisfy your concern? The two things are now more tightly coupled and configured in the same file.
</blockquote></details>

This is great!

**Review by nkinkade — COMMENTED** [review]
I don't believe there is anything blocking or pending that prevents this from being merged.

> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/907#-:-O8nJLr07xU7uEa-RMsm:baws5wq)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[`k8s/custom-resource-definitions/multi-networkpolicy.jsonnet` line 1 at r1](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8cGWwG2B9FDxxIZKPH:-O8nGfuF1peCIr6DyjcW:bkogbzo) ([raw file](https://github.com/m-lab/k8s-support/blob/64b4d5f5791288c3313375513740508894ade895/k8s/custom-resource-definitions/multi-networkpolicy.jsonnet#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you!
</blockquote></details>

If/when v1beta2 gets fixed/deployed upstream, then we could possible get rid of this entire file and simply apply the CRD using the URL of the upstream schema.yml file.
___
*[`k8s/daemonsets/core/multi-networkpolicy.jsonnet` line 50 at r2](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8nC-If-BYeUnxF_UD1:-O8nIpAF4pVTClkl-lkY:b7nh1wo) ([raw file](https://github.com/m-lab/k8s-support/blob/bdf364cc5ce701511bb94c4fdb3006edb82a3bb1/k8s/daemonsets/core/multi-networkpolicy.jsonnet#L50)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Clarifying: this is where someone might add `--custom-v4-igress-rule-file` and the others? If so, please make that explicit. The earlier file mentions "flags to multi-networkpolicy" and I see this is "multi-networkpolicy-iptables". If it's not this, where are the "multi-networkpolicy" flags?
</blockquote></details>

That is correct. The args array in this file is where those flags would go to define custom rules. I added the flags, but commented them out, and additionally added a small explanation. I have also updated config/multi-networkpolicy.jsonnet with additional comments to clarify how all this works.

**Review by stephen-soltesz — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 7 of 13 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/k8s-support/907)* status: 0 of 1 approvals obtained

___
*[`k8s/daemonsets/core/multi-networkpolicy.jsonnet` line 50 at r2](https://reviewable.io/reviews/m-lab/k8s-support/907#-O8nC-If-BYeUnxF_UD1:-O8nSXIe7d27x2J8cdSQ:bxztp5h) ([raw file](https://github.com/m-lab/k8s-support/blob/bdf364cc5ce701511bb94c4fdb3006edb82a3bb1/k8s/daemonsets/core/multi-networkpolicy.jsonnet#L50)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

That is correct. The args array in this file is where those flags would go to define custom rules. I added the flags, but commented them out, and additionally added a small explanation. I have also updated config/multi-networkpolicy.jsonnet with additional comments to clarify how all this works.
</blockquote></details>

Beautiful!

**Pull request merged**
